
production:
  adapter: postgresql
  encoding: unicode
  database: forestchat_production

  pool: 5



development:
  adapter: postgresql
  encoding: unicode
  database: forestchat_development
  pool: 5
  username: postgres
  password: 2020

test:
  adapter: postgresql
  encoding: unicode
  database: forestchat_test
  pool: 5
  username: postgres
  password: 2020
